package com.fleetmanager.fcm

/**
 * Shared constants for FCM payload keys and actions.
 * Keeping them in a single place ensures both notification handling and
 * navigation logic stay consistent with the values generated by Cloud Functions.
 */
object NotificationConstants {
    const val KEY_ACTION = "action"
    const val KEY_MISSING_DATE = "missingDate"
    const val KEY_CHANNEL_ID = "channel_id"

    const val ACTION_MISSING_INCOME = "missing_income"
}
