name: Android Build

on:
  push:
    branches:
      - main  # Change cette ligne si ta branche principale s'appelle différemment

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > app/google-services.json

      - name: Build APK
        run: ./gradlew :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fleettrackr-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
