name: Build Debug APK

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    env:
      JAVA_OPTS: "-Xmx4g"

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: FleetManager-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
