name: Build Debug APK

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android
            ${{ env.ANDROID_SDK_ROOT }}
          key: android-sdk-${{ runner.os }}-v1
          restore-keys: |
            android-sdk-${{ runner.os }}-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Check Android SDK Cache Size (
