name: Build Debug APK

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Delete Gradle and build cache
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon
          rm -rf ~/.gradle/native
          rm -rf app/build

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Clean project
        run: ./gradlew clean

      - name: Print lambda lines to confirm source version
        run: |
          echo "DashboardScreen.kt:"
          grep "rememberStableLambda" app/src/main/java/com/fleetmanager/ui/screens/dashboard/DashboardScreen.kt || echo "Line not found"
          echo "---"
          echo "EntryListScreen.kt:"
          grep "rememberStableLambda" app/src/main/java/com/fleetmanager/ui/screens/entry/EntryListScreen.kt || echo "Line not found"

      - name: Build APK with Gradle
        run: ./gradlew :app:assembleDebug --no-build-cache --no-configuration-cache --parallel --daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'pull_request'
        with:
          name: app-debug-${{ github.run_number }}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
          compression-level: 6
