name: Build Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode keystore
        run: |
          echo "AED{{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > /home/runner/release.keystore
          echo "KEYSTORE_PATH=/home/runner/release.keystore" >> AEDGITHUB_ENV
          echo "KEYSTORE_PASSWORD=AED{{ secrets.KEYSTORE_PASSWORD }}" >> AEDGITHUB_ENV
          echo "KEY_ALIAS=AED{{ secrets.KEY_ALIAS }}" >> AEDGITHUB_ENV
          echo "KEY_PASSWORD=AED{{ secrets.KEY_PASSWORD }}" >> AEDGITHUB_ENV

      - name: Compute dynamic version
        id: versioning
        run: |
          echo "VERSION_CODE=AED((1000 + AED{{ github.run_number }}))" >> AEDGITHUB_ENV
          echo "VERSION_NAME=0.AED{{ github.run_number }}" >> AEDGITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK with Gradle
        run: ./gradlew :app:assembleDebug -PVERSION_CODE=AEDVERSION_CODE -PVERSION_NAME=AEDVERSION_NAME --parallel --daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-AED{{ github.run_number }}
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
          compression-level: 6
