name: Recover Keystore

on:
  workflow_dispatch: # Permet de lancer le workflow manuellement

jobs:
  recover:
    runs-on: ubuntu-latest
    steps:
      - name: Decode keystore from base64
        run: |
          echo "$KEYSTORE_BASE64" > keystore.b64
          base64 --decode keystore.b64 > my-release-key.jks
          ls -lh my-release-key.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Upload keystore as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-release-keystore
          path: my-release-key.jks
